# -*- coding: utf-8 -*-
"""FINAL UI DREAMIFYipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ssskHBJ0CMm10HipQba9fp_C-eY2M6Js
"""



# Wipe conflicting installs
!pip uninstall -y diffusers transformers accelerate huggingface-hub

# Torch for CUDA 12 Colab
!pip -q install "torch==2.3.1+cu121" "torchvision==0.18.1+cu121" \
  --index-url https://download.pytorch.org/whl/cu121

# Compatible HF stack
!pip -q install \
  "diffusers==0.25.0" \
  "transformers==4.37.2" \
  "accelerate==0.26.0" \
  "huggingface-hub==0.25.2" \
  safetensors imageio[ffmpeg] moviepy
!pip -q install --upgrade accelerate==0.30.1 peft==0.11.1
import os
os.makedirs("outputs/frames", exist_ok=True)
!pip install -q --upgrade pip setuptools wheel
!pip install moviepy

from diffusers import StableDiffusionPipeline
import torch

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16 if torch.cuda.is_available() else None,
    safety_checker=None,
).to("cuda" if torch.cuda.is_available() else "cpu")

img = pipe("a tiny robot watering a sunflower").images[0]
display(img)

def model(prompt):
  from diffusers import StableDiffusionPipeline
  import torch, time

  device = "cuda" if torch.cuda.is_available() else "cpu"
  pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", safety_checker=None)
  pipe = pipe.to(device)


  n_frames = 6

  for i in range(n_frames):
    seed = 42 + i*10
    generator = torch.Generator(device=device).manual_seed(seed)
    start = time.time()
    out = pipe(prompt, guidance_scale=7.5, num_inference_steps=30, generator=generator)
    image = out.images[0]
    image.save(f"outputs/frames/frame_{i:02d}.png")
    print(f"Saved frame {i} (seed={seed}) in {time.time()-start:.1f}s")
  # zip all frames into one file
  !zip -r frames.zip outputs/frames

# download the zip file to your laptop
  #from google.colab import files
  #files.download("frames.zip")
  #from google.colab import files
  #files.download("outputs/frames/frame_00.png")
  from moviepy.editor import ImageSequenceClip
  import glob

  frames = sorted(glob.glob("outputs/frames/*.png"))
  clip = ImageSequenceClip(frames, fps=len(frames)/3)   # 3 seconds long
  clip.write_videofile("outputs/dreamify_demo.mp4", codec="libx264")
  print("Saved dreamify_demo.mp4")
  # at the end of model()
  return {
    "ok": True,
    "video": "/outputs/dreamify_demo.mp4",
    "frames_zip": "/outputs/frames.zip"}

# ---------- FastAPI app ----------
from fastapi import FastAPI, Form
from fastapi.responses import JSONResponse, HTMLResponse
from fastapi.staticfiles import StaticFiles

app = FastAPI()

# ✅ either create dir first (we did) OR set check_dir=False here
app.mount("/outputs", StaticFiles(directory="outputs", check_dir=False), name="outputs")

@app.get("/", response_class=HTMLResponse)
def home():
    return """<!doctype html> ... (your same HTML from message) ... """

@app.post("/generate")
def generate(prompt: str = Form(...)):
    try:
        return JSONResponse(model(prompt))
    except Exception as e:
        return JSONResponse({"ok": False, "error": str(e)}, status_code=500)

from fastapi import FastAPI, Form
from fastapi.responses import JSONResponse, HTMLResponse, FileResponse
from fastapi.staticfiles import StaticFiles

app = FastAPI()

# serve everything inside /outputs at /outputs/<file>
app.mount("/outputs", StaticFiles(directory="outputs"), name="outputs")

# simple HTML UI
@app.get("/", response_class=HTMLResponse)
def home():
    return """
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Dreamify — Prompt → Video/GIF</title>
<meta name="viewport" content="width=device-width, initial-scale=1"/>

<style>
  /* ====== GLOBAL ====== */
  body{
    margin:0;
    padding:0;
    font-family: 'Segoe UI', Roboto, sans-serif;
    background: radial-gradient(circle at top, #0a0f24, #02040a 70%);
    color:#e7ecff;
    min-height:100vh;
    display:flex;
    justify-content:center;
    align-items:flex-start;
    padding-top:60px;
  }
  *{ box-sizing:border-box; }

  /* ====== CARD ====== */
  .card{
    width:90%;
    max-width:760px;
    background: rgba(20,25,45,0.55);
    border:1px solid rgba(70,90,255,0.25);
    backdrop-filter: blur(14px);
    border-radius:16px;
    padding:32px;
    box-shadow: 0 0 25px rgba(0,150,255,0.25);
    animation: fadeIn 0.5s ease-out;
  }

  h2{
    margin-top:0;
    font-size:1.9rem;
    font-weight:600;
    letter-spacing:0.5px;
    background: linear-gradient(90deg,#4cc9ff,#b74bff);
    -webkit-background-clip:text;
    -webkit-text-fill-color:transparent;
  }

  p.muted{ color:#9aa8c8; }

  /* ====== INPUT ROW ====== */
  .row{ display:flex; gap:12px; margin-top:18px; }
  .row input{
    flex:1;
    padding:14px 16px;
    font-size:1rem;
    border:2px solid rgba(110,140,255,0.25);
    border-radius:10px;
    background:rgba(0,10,30,0.6);
    color:#eaffff;
    outline:none;
    transition:0.2s;
  }
  .row input:focus{
    border-color:#6ab8ff;
    box-shadow:0 0 10px #4cc9ff77;
  }

  /* ====== NEON BUTTON ====== */
  button{
    padding:14px 22px;
    font-size:1rem;
    font-weight:600;
    letter-spacing:0.5px;
    border:none;
    color:white;
    cursor:pointer;
    background:linear-gradient(90deg,#386BFF,#9336FD);
    border-radius:10px;
    box-shadow:0 0 12px rgba(100,120,255,0.45);
    transition:0.25s;
  }
  button:hover{
    transform:translateY(-2px) scale(1.03);
    box-shadow:0 0 18px rgba(140,90,255,0.65);
  }
  button:disabled{
    opacity:0.5; cursor:not-allowed;
  }

  /* ====== STATUS / VIDEO ====== */
  #spinner{ margin-top:14px; font-size:0.95rem; color:#9ecbff; }
  #msg{ margin-top:10px; font-size:1rem; }
  video{
    width:100%;
    margin-top:18px;
    border-radius:12px;
    box-shadow:0 0 18px rgba(0,180,255,0.35);
  }

  .links{ margin-top:14px; }
  .links a{
    margin-right:18px;
    color:#83c8ff;
    font-weight:500;
    text-decoration:none;
  }
  .links a:hover{ text-decoration:underline; }

  @keyframes fadeIn{
    from{ opacity:0; transform:translateY(10px); }
    to{ opacity:1; transform:translateY(0); }
  }
</style>
</head>

<body>
  <div class="card">
    <h2>🎬 Dreamify — Prompt → Video/GIF</h2>
    <p class="muted">Enter a prompt and click Generate. Your prompt is sent to <code>/generate</code> which runs <code>model(prompt)</code>.</p>

    <form id="f" class="row">
      <input name="prompt" id="prompt" placeholder="A neon jellyfish flying through cyberpunk clouds…" required/>
      <button id="btn" type="submit">Generate</button>
    </form>

    <p id="spinner">⏳ Generating… first run may take longer</p>
    <p id="msg"></p>

    <video id="v" controls style="display:none"></video>

    <div class="links" id="links" style="display:none">
      <a id="dl_video" download>Download MP4</a>
      <a id="dl_zip" download>Download frames.zip</a>
    </div>
  </div>

<script>
  const f = document.getElementById('f');
  const btn = document.getElementById('btn');
  const msg = document.getElementById('msg');
  const spin = document.getElementById('spinner');
  const v = document.getElementById('v');
  const links = document.getElementById('links');
  const aVid = document.getElementById('dl_video');
  const aZip = document.getElementById('dl_zip');

  f.onsubmit = async (e) => {
    e.preventDefault();
    msg.textContent = "";
    v.style.display = "none";
    links.style.display = "none";
    spin.style.display = "inline";
    btn.disabled = true;

    try{
      const res = await fetch('/generate', { method:'POST', body: new FormData(f) });
      const j = await res.json();
      if(j.ok){
        v.src = j.video;
        v.style.display = "block";
        links.style.display = "block";
        aVid.href = j.video;
        aZip.href = j.frames_zip;
        msg.textContent = "✅ Done!";
      } else {
        msg.textContent = "❌ " + (j.error || 'Unknown error');
      }
    } catch(err){
      msg.textContent = "❌ Network error: " + err;
    } finally {
      spin.style.display = "none";
      btn.disabled = false;
    }
  };
</script>
</body>
</html>
"""

@app.post("/generate")
def generate(prompt: str = Form(...)):
    try:
        result = model(prompt)  # <-- YOUR FUNCTION IS CALLED HERE
        return JSONResponse(result)
    except Exception as e:
        return JSONResponse({"ok": False, "error": str(e)}, status_code=500)

import uvicorn, threading
PORT = 8000

def run():
    uvicorn.run(app, host="0.0.0.0", port=PORT, log_level="info")

thread = threading.Thread(target=run, daemon=True)
thread.start()
print(f"✅ FastAPI running at http://0.0.0.0:{PORT} (Colab)")

!pip -q install pyngrok

from pyngrok import ngrok
from pyngrok.conf import PyngrokConfig

NGROK_TOKEN = "34uX5DjEksuJQpTpfIEwGJMbuOW_7e4Xtk7LRcBPbMXr8SHVb".strip()
tunnel = ngrok.connect(PORT, "http", bind_tls=True, pyngrok_config=PyngrokConfig(auth_token=NGROK_TOKEN))
print("🌍 Public URL:", tunnel.public_url)

!pip -q install --upgrade \
  "huggingface-hub==0.25.2" \
  "transformers==4.44.2" \
  "diffusers==0.30.0" \
  "accelerate==0.34.2" \
  "safetensors" \
  "imageio[ffmpeg]" "moviepy"